name: Create Base Image

on:
  workflow_dispatch:

jobs:
  create-base-image:
    name: Create Base Image
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GH_CLI }}
    steps:
    - name: checkout current repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run Docker Build
      run: |
        ls -la
        docker build -t hunkoraboni/minha-imagem:1.0 -t hunkoraboni/minha-imagem:latest -f Dockerfile.base .
        docker images
        docker push --all-tags ghcr.io/hunkoraboni/minha-imagem
